print("I'm learning Git merge conflicts")
name = input('Please enter your name: ')
last_name = input('Please enter your last name: ')
nick = input('Please enter your nickname: ')
print('Hi, {} {} aka {}!'.format(name, last_name, nick))
